port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
proxies:
- name: GetXConfig-1
  type: vless
  server: 57.129.53.181
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-3
  type: vless
  server: oodplkgju.vjdkem.mmejdus.ksmajww.cncjskwisuxjs.infinityofconnectedminds.com
  port: 3090
  uuid: dc923edf-9962-4817-bd51-f43f696c5fbc
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-5
  type: vless
  server: 140.248.155.104
  port: 443
  uuid: 17f100d3-4b31-47f9-b8df-94d1a723d43e
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-7
  type: vless
  server: kzcdn1.suio.me
  port: 443
  uuid: 6ca2c654-53b3-4ac1-a2ef-c4b4ee88727a
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-9
  type: vless
  server: io.market.iran-rom.ir
  port: 50330
  uuid: 74f6348b-bc9a-4175-93f9-080afda56da8
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-11
  type: vless
  server: est.top.subtrust.ru
  port: 443
  uuid: 3130fccb-e72e-468d-b2ce-0721bb3058c8
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-25
  type: vless
  server: 89.35.73.250
  port: 443
  uuid: 30dc00c9-16c5-4573-b5b2-532940febfd6
  udp: true
  tls: false
  skip-cert-verify: true
- name: meliproxyy-30
  type: vless
  server: my4.tehranhost.mom
  port: 37004
  uuid: 88df4b42-f464-4a5d-b239-031cb613fd20
  udp: true
  tls: false
  skip-cert-verify: true
- name: '@RUSSIAPROXYY 🇷🇺-32'
  type: vmess
  server: 8.210.141.149
  port: 443
  uuid: 5ecc3086-93cf-42e3-956b-f2180e042537
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
- name: '@EsTunnel - Psiphon+V2rayNG-33'
  type: vmess
  server: gsmvpn.gsmvx.com
  port: 5006
  uuid: b17345b9-6266-47f2-a473-8c57cbfe9ef9
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: '@Hiddify_Nexttt + Psiphon-34'
  type: vmess
  server: gsmvpn.gsmvx.com
  port: 5006
  uuid: b17345b9-6266-47f2-a473-8c57cbfe9ef9
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-35
  type: vless
  server: snt1.shahramv1.site
  port: 443
  uuid: 14db8096-7800-4cb8-bb52-1856e3b65785
  udp: true
  tls: true
  skip-cert-verify: true
- name: vmess_iran-36
  type: vless
  server: 54.93.56.163
  port: 22224
  uuid: 05519058-d2ac-4f28-9e4a-2b2a1386749e
  udp: true
  tls: true
  skip-cert-verify: true
- name: vmess_iran-37
  type: vless
  server: 199.241.138.38
  port: 25631
  uuid: 14b02e2a-8930-4afb-8412-ea4a4954ca5b
  udp: true
  tls: true
  skip-cert-verify: true
- name: vmess_iran-38
  type: vless
  server: emg6.saipasamandemg6.sbs
  port: 2006
  uuid: 15fc3678-bb1e-4c72-8ff7-2d477f1b8434
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-39
  type: trojan
  server: 54.93.56.163
  port: 22222
  password: telegram-id-privatevpns
  udp: true
  tls: true
  skip-cert-verify: true
- name: vmess_iran-47
  type: vless
  server: viptun2.persianv2.ir
  port: 2096
  uuid: 3898b276-c444-4d61-a563-7e69fc389026
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-48
  type: vless
  server: outbounde.iran-mehrbu.ir
  port: 16446
  uuid: 49bc99e9-305a-4045-a609-a258e8b2b76d
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-49
  type: vless
  server: viptun2.persianv2.ir
  port: 2096
  uuid: 3898b276-c444-4d61-a563-7e69fc389026
  udp: true
  tls: false
  skip-cert-verify: true
proxy-groups:
- name: AUTO
  type: url-test
  proxies:
  - GetXConfig-1
  - GetXConfig-3
  - GetXConfig-5
  - GetXConfig-7
  - GetXConfig-9
  - GetXConfig-11
  - Farah_VPN-25
  - meliproxyy-30
  - '@RUSSIAPROXYY 🇷🇺-32'
  - '@EsTunnel - Psiphon+V2rayNG-33'
  - '@Hiddify_Nexttt + Psiphon-34'
  - vmess_iran-35
  - vmess_iran-36
  - vmess_iran-37
  - vmess_iran-38
  - vmess_iran-39
  - vmess_iran-47
  - vmess_iran-48
  - vmess_iran-49
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,AUTO
