port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
proxies:
- name: GetXConfig-1
  type: vless
  server: 185.193.28.168
  port: 2096
  uuid: 1a25f8ad-cad2-4e93-b5bf-34e42bcac02a
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-3
  type: vless
  server: vip-80.f-sub.cfd
  port: 1517
  uuid: 4551ccd5-0ff3-4064-8478-28182495661f
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-5
  type: vless
  server: ip.hamrahto.com
  port: 8443
  uuid: 9e35a3d0-1309-4697-a61c-e898e6312c35
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-7
  type: vless
  server: www.fastly.com
  port: 80
  uuid: dd0cfef0-fda9-47ec-8a65-49d7bc004f82
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-9
  type: vless
  server: 185.162.231.138
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-11
  type: vless
  server: chatgpt.com
  port: 443
  uuid: 2ad80cff-5ef8-416a-a663-22c147264faa
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-13
  type: vless
  server: 46.62.128.207
  port: 443
  uuid: 309fa273-6579-4cb2-9143-7cad50401eba
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-15
  type: vless
  server: 18.159.99.186
  port: 22224
  uuid: 05519058-d2ac-4f28-9e4a-2b2a1386749e
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-17
  type: vless
  server: 162.251.82.187
  port: 443
  uuid: 9bd4142c-7025-4405-9350-33851fdb4ecc
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-19
  type: vless
  server: 162.159.152.4
  port: 443
  uuid: e4824193-4f54-453b-d037-88368e85ef0e
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-21
  type: vless
  server: 45.148.31.0
  port: 15855
  uuid: e4fc4761-154f-490e-bbaa-b4fa193f1073
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-23
  type: vless
  server: 170.64.238.91
  port: 39218
  uuid: fcbead98-fef8-4707-bd4f-1278935c9a44
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-25
  type: vless
  server: 188.244.122.136
  port: 80
  uuid: d5657005-94be-4198-80cf-f9a814bad404
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-27
  type: vless
  server: parsaprivae.isgood.host
  port: 22750
  uuid: cc1d0ad9-d4ac-4b7e-a9ba-048fa96a9e1e
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-29
  type: vless
  server: 35.181.225.239
  port: 22224
  uuid: 05519058-d2ac-4f28-9e4a-2b2a1386749e
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-31
  type: vless
  server: 188.244.122.136
  port: 80
  uuid: d5657005-94be-4198-80cf-f9a814bad404
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-33
  type: vless
  server: 89.125.48.112
  port: 443
  uuid: fd325093-cdb5-4a73-980e-af2ec0444310
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-35
  type: vless
  server: a3mcxej4pmzf.hosted-in.p7d.ir
  port: 2053
  uuid: 5a94a48d-242c-4595-a620-66296d10463f
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-37
  type: vless
  server: 162.251.82.187
  port: 443
  uuid: 9bd4142c-7025-4405-9350-33851fdb4ecc
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-39
  type: vless
  server: 104.16.139.37
  port: 443
  uuid: 98aec3c3-d957-4363-9933-018e533c7c06
  udp: true
  tls: true
  skip-cert-verify: true
- name: 🇨🇳 Join+Telegram:@Farah_VPN 🇨🇳-41
  type: vmess
  server: n1747624282.lie5d.cyou
  port: 443
  uuid: 30109222-8c53-41bc-9781-a01cdeb68e4c
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-47
  type: vless
  server: 37.156.45.227
  port: 36261
  uuid: cb57b920-cd95-4bbf-bd8c-9e58833fcc5c
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-50
  type: vless
  server: 51.250.0.147
  port: 443
  uuid: eb071647-72a6-46be-8e89-ff3d228d52f6
  udp: true
  tls: false
  skip-cert-verify: true
- name: 🇨🇳 Join+Telegram:@Farah_VPN 🇨🇳-52
  type: vmess
  server: n1753356361.lie5d.cyou
  port: 443
  uuid: cdfd9787-dac8-4c1e-9ae5-104e23a9d994
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-55
  type: vless
  server: pqh29v3.globalfymain.com
  port: 8880
  uuid: 8dc7722c-2767-4eea-a28b-2f8daacc07e3
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-58
  type: vless
  server: 38.244.215.124
  port: 443
  uuid: 28f9da30-cd81-4726-86a9-d2e17b14decc
  udp: true
  tls: false
  skip-cert-verify: true
- name: 🇺🇸 Join+Telegram:@Farah_VPN 🇺🇸-61
  type: vmess
  server: jmkl.6hh.ccwu.cc
  port: 80
  uuid: 5f6c3f92-7220-4275-b34d-57c04db3f967
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-63
  type: vless
  server: 87.229.97.154
  port: 443
  uuid: d65cc14c-f53f-4fe2-b262-97856601319c
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-65
  type: vless
  server: 188.165.137.202
  port: 8443
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-67
  type: vless
  server: 5.254.85.151
  port: 443
  uuid: ccedb1b1-35f3-46d1-a85a-c699eef5f3e1
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-69
  type: vless
  server: 1.cdnconn.com
  port: 23335
  uuid: e384913f-8863-47b4-8858-a84b68abb4a6
  udp: true
  tls: false
  skip-cert-verify: true
- name: meliproxyy-71
  type: vless
  server: respina24.gdsrguydsrghj.ir
  port: 1010
  uuid: bf923569-ff69-4638-b1d3-38e3348d9571
  udp: true
  tls: false
  skip-cert-verify: true
- name: proxy_kafee-73
  type: vless
  server: hub1.wiziii.xyz
  port: 8085
  uuid: 4bef06d1-7535-4ba5-8446-bd6b94e6b150
  udp: true
  tls: false
  skip-cert-verify: true
- name: proxy_kafee-74
  type: vless
  server: moh1.wiziii.xyz
  port: 8085
  uuid: 4bef06d1-7535-4ba5-8446-bd6b94e6b150
  udp: true
  tls: false
  skip-cert-verify: true
- name: proxy_kafee-75
  type: vless
  server: gb1.wiziii.xyz
  port: 8085
  uuid: 4bef06d1-7535-4ba5-8446-bd6b94e6b150
  udp: true
  tls: false
  skip-cert-verify: true
- name: proxy_kafee-76
  type: vless
  server: gr1.wiziii.xyz
  port: 8085
  uuid: 4bef06d1-7535-4ba5-8446-bd6b94e6b150
  udp: true
  tls: false
  skip-cert-verify: true
- name: proxy_kafee-81
  type: vless
  server: mtn3.persiangames.link
  port: 2472
  uuid: 25b8253c-459d-4246-feff-8704baeefaa6
  udp: true
  tls: false
  skip-cert-verify: true
- name: 'Telegram:  @CroSs_Guildd-83'
  type: vmess
  server: ir4.vaxon1.click
  port: 443
  uuid: cb3c3fe5-e3ab-494f-8302-0e48f93db398
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-84
  type: vless
  server: shop.khalijservers1.top
  port: 7432
  uuid: ed9cbe67-25c5-4d41-a29d-891dceda33ff
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-87
  type: vless
  server: 94.101.191.11
  port: 80
  uuid: d9e40483-30ae-4076-8c8d-8d380f46ea33
  udp: true
  tls: false
  skip-cert-verify: true
- name: '@proxygodratmand قطع شدی بیا چنل فقط-89'
  type: vmess
  server: g1.sroushesdi.xyz
  port: 2087
  uuid: aafd464a-630e-4dc1-907c-43d8010ae26e
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-90
  type: vless
  server: 212.80.19.204
  port: 8081
  uuid: 598f87d5-b28c-449d-89d0-2b199bf83b55
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-91
  type: vless
  server: ia.a.clearriverlab.sbs
  port: 8081
  uuid: 598f87d5-b28c-449d-89d0-2b199bf83b55
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-92
  type: vless
  server: germany.heliyadak.ir
  port: 52678
  uuid: 589c0f96-7ab5-470b-8f1d-cb87e09d2138
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-93
  type: vless
  server: dns5.golden-ping.ir
  port: 16662
  uuid: 8be1f2ce-ac71-49cc-b08a-b396b6053b00
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-94
  type: vless
  server: respina24.gdsrguydsrghj.
  port: null
  uuid: bf923569-ff69-4638-b1d3-38e3348d9571
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-95
  type: vless
  server: iran.yarnovin.com
  port: 49997
  uuid: 2444a7f2-6c80-4bc2-838b-342371b0d35a
  udp: true
  tls: false
  skip-cert-verify: true
- name: vmess_iran-103
  type: vless
  server: shop.khalijservers1.top
  port: 7432
  uuid: ed9cbe67-25c5-4d41-a29d-891dceda33ff
  udp: true
  tls: false
  skip-cert-verify: true
- name: Spotify_Porteghali-105
  type: vless
  server: grr.x2net.top
  port: 443
  uuid: 194d0fc3-800b-44a1-be2f-3486051ab9b3
  udp: true
  tls: true
  skip-cert-verify: true
- name: '@Spotify_Porteghali 7390-107'
  type: vmess
  server: mac.pkpowerking.xyz
  port: 34082
  uuid: 91dce55e-47c7-4176-be61-21b1122d9c40
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: Spotify_Porteghali-109
  type: vless
  server: it0.xn--fjqyexxidv2znoe9rk1n8agb1e05q.xn--6qq79v59whul.com
  port: 2342
  uuid: 6aca4d75-3b81-4d29-a951-3b8d5dd7470e
  udp: true
  tls: false
  skip-cert-verify: true
proxy-groups:
- name: AUTO
  type: url-test
  proxies:
  - GetXConfig-1
  - GetXConfig-3
  - GetXConfig-5
  - GetXConfig-7
  - GetXConfig-9
  - GetXConfig-11
  - GetXConfig-13
  - GetXConfig-15
  - GetXConfig-17
  - GetXConfig-19
  - GetXConfig-21
  - GetXConfig-23
  - GetXConfig-25
  - GetXConfig-27
  - GetXConfig-29
  - GetXConfig-31
  - GetXConfig-33
  - GetXConfig-35
  - GetXConfig-37
  - Farah_VPN-39
  - 🇨🇳 Join+Telegram:@Farah_VPN 🇨🇳-41
  - Farah_VPN-47
  - Farah_VPN-50
  - 🇨🇳 Join+Telegram:@Farah_VPN 🇨🇳-52
  - Farah_VPN-55
  - Farah_VPN-58
  - 🇺🇸 Join+Telegram:@Farah_VPN 🇺🇸-61
  - Farah_VPN-63
  - Farah_VPN-65
  - Farah_VPN-67
  - Farah_VPN-69
  - meliproxyy-71
  - proxy_kafee-73
  - proxy_kafee-74
  - proxy_kafee-75
  - proxy_kafee-76
  - proxy_kafee-81
  - 'Telegram:  @CroSs_Guildd-83'
  - vmess_iran-84
  - vmess_iran-87
  - '@proxygodratmand قطع شدی بیا چنل فقط-89'
  - vmess_iran-90
  - vmess_iran-91
  - vmess_iran-92
  - vmess_iran-93
  - vmess_iran-94
  - vmess_iran-95
  - vmess_iran-103
  - Spotify_Porteghali-105
  - '@Spotify_Porteghali 7390-107'
  - Spotify_Porteghali-109
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,AUTO
