port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
proxies:
- name: GetXConfig-1
  type: vless
  server: 57.129.53.181
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-3
  type: vless
  server: oodplkgju.vjdkem.mmejdus.ksmajww.cncjskwisuxjs.infinityofconnectedminds.com
  port: 3090
  uuid: dc923edf-9962-4817-bd51-f43f696c5fbc
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-5
  type: vless
  server: 140.248.155.104
  port: 443
  uuid: 17f100d3-4b31-47f9-b8df-94d1a723d43e
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-7
  type: vless
  server: kzcdn1.suio.me
  port: 443
  uuid: 6ca2c654-53b3-4ac1-a2ef-c4b4ee88727a
  udp: true
  tls: true
  skip-cert-verify: true
- name: GetXConfig-9
  type: vless
  server: io.market.iran-rom.ir
  port: 50330
  uuid: 74f6348b-bc9a-4175-93f9-080afda56da8
  udp: true
  tls: false
  skip-cert-verify: true
- name: GetXConfig-11
  type: vless
  server: est.top.subtrust.ru
  port: 443
  uuid: 3130fccb-e72e-468d-b2ce-0721bb3058c8
  udp: true
  tls: false
  skip-cert-verify: true
- name: 🇰🇷 Join+Telegram:@Farah_VPN 🇰🇷-13
  type: vmess
  server: 132.145.80.230
  port: 80
  uuid: 5155860e-d07d-46c3-9128-3afbd84626c7
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-16
  type: trojan
  server: jpbgp.netvigor.cc
  port: 19128
  password: gcuCpQfaiVeDBdWG
  udp: true
  tls: true
  skip-cert-verify: true
- name: 🇺🇸 Join+Telegram:@Farah_VPN 🇺🇸-17
  type: vmess
  server: 82.198.246.9
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-19
  type: vless
  server: 63.141.128.9
  port: 443
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-21
  type: vless
  server: 185.135.9.138
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-23
  type: vless
  server: 51.158.206.93
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-25
  type: vless
  server: 104.129.166.138
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-27
  type: vless
  server: dnew.cc
  port: 443
  uuid: ce069292-c8bf-40dd-a6b1-87818a1e64e9
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-29
  type: vless
  server: 172.64.149.54
  port: 8443
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  skip-cert-verify: true
- name: 🇩🇪 Join+Telegram:@Farah_VPN 🇩🇪-31
  type: vmess
  server: heu83ujieiwoeu83j2ewjehuwehu8.dentiscan.ca
  port: 80
  uuid: e2923bc6-8204-4768-98ea-379d48ea8a7a
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-34
  type: vless
  server: www.digitalcommerce360.com
  port: 2053
  uuid: 8c4604ef-749c-4b56-adf1-7da405002a21
  udp: true
  tls: true
  skip-cert-verify: true
- name: 🇭🇰 Join+Telegram:@Farah_VPN 🇭🇰-36
  type: vmess
  server: 47.244.120.197
  port: 36703
  uuid: 45b83519-9c4f-4052-a11b-02e017b636d4
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: 🇭🇰 Join+Telegram:@Farah_VPN 🇭🇰-38
  type: vmess
  server: 47.239.69.43
  port: 56698
  uuid: 1f2d0b2b-e214-4fc1-92cc-1c230be78d7c
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-40
  type: vless
  server: 162.159.12.151
  port: 443
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-42
  type: vless
  server: 104.18.12.149
  port: 443
  uuid: b60e5c32-3d4e-425c-a785-a36cd0621a72
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-44
  type: vless
  server: xsus.xs-us.net
  port: 29876
  uuid: b6096ffb-656a-4fec-8840-0d032089a3e0
  udp: true
  tls: true
  skip-cert-verify: true
- name: Farah_VPN-46
  type: vless
  server: 51.158.206.87
  port: 23576
  uuid: 48ff2b70-e180-582f-8866-d9a2edeed5f5
  udp: true
  tls: false
  skip-cert-verify: true
- name: Farah_VPN-48
  type: vless
  server: 139.64.235.238
  port: 2096
  uuid: 6202b230-417c-4d8e-b624-0f71afa9c75d
  udp: true
  tls: true
  skip-cert-verify: true
- name: meliproxyy-50
  type: vless
  server: varzesh3.com
  port: 2052
  uuid: 10219eb2-e64a-4557-bd61-5cfd6e1f2281
  udp: true
  tls: false
  skip-cert-verify: true
- name: Spotify_Porteghali-53
  type: trojan
  server: 95.38.189.135
  port: 40443
  password: humanity
  udp: true
  tls: true
  skip-cert-verify: true
proxy-groups:
- name: AUTO
  type: url-test
  proxies:
  - GetXConfig-1
  - GetXConfig-3
  - GetXConfig-5
  - GetXConfig-7
  - GetXConfig-9
  - GetXConfig-11
  - 🇰🇷 Join+Telegram:@Farah_VPN 🇰🇷-13
  - Farah_VPN-16
  - 🇺🇸 Join+Telegram:@Farah_VPN 🇺🇸-17
  - Farah_VPN-19
  - Farah_VPN-21
  - Farah_VPN-23
  - Farah_VPN-25
  - Farah_VPN-27
  - Farah_VPN-29
  - 🇩🇪 Join+Telegram:@Farah_VPN 🇩🇪-31
  - Farah_VPN-34
  - 🇭🇰 Join+Telegram:@Farah_VPN 🇭🇰-36
  - 🇭🇰 Join+Telegram:@Farah_VPN 🇭🇰-38
  - Farah_VPN-40
  - Farah_VPN-42
  - Farah_VPN-44
  - Farah_VPN-46
  - Farah_VPN-48
  - meliproxyy-50
  - Spotify_Porteghali-53
  url: http://www.gstatic.com/generate_204
  interval: 300
rules:
- MATCH,AUTO
